name: Backend Tests

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'my-notes-and-tasks-backend/**'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'my-notes-and-tasks-backend/**'

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]

    defaults:
      run:
        working-directory: ./my-notes-and-tasks-backend

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './my-notes-and-tasks-backend/package-lock.json'

    - name: Install dependencies
      run: npm ci

    - name: Run unit tests
      run: npm run test:unit

    - name: Run integration tests
      run: npm run test:integration

    - name: Run all tests with coverage
      run: npm run test:coverage

    - name: Upload coverage reports
      uses: codecov/codecov-action@v4
      if: matrix.node-version == '20.x'
      with:
        file: ./my-notes-and-tasks-backend/coverage/lcov.info
        flags: backend
        name: backend-coverage
        fail_ci_if_error: false

    - name: Upload test results
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Backend Test Results (Node ${{ matrix.node-version }})
        path: './my-notes-and-tasks-backend/test-results/junit.xml'
        reporter: jest-junit
        fail-on-error: false